title: Worldgen Docs
email: apollo404mc@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Documentation and guides on the data-driven world generation
  system for Minecraft: Java Edition.
baseurl: "/worldgen-docs" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ApolloDatapacks

# Build settings
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed

# JTD Theme Settings
search_enabled: true
color_scheme: dark

# JTD Footer
last_edit_timestamp: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/ApolloDatapacks/worldgen-docs/"
gh_edit_branch: "gh-pages"
gh_edit_view_mode: "tree"

# JTD Callouts
callouts:
  warning:
    title: Warning
    color: red
  highlight:
    color: yellow
  note:
    title: Note
    color: purple
  important:
    title: Important
    color: blue
  new: # For minor updates maybe?
    title: New
    color: green